### ISSUE TITLE
IOS based on model

### ISSUE THREAD

**Issue by helpdeskdan** [derek-shnosh/ztp-watcher#1]
Not hard - an snmp call and a dictionary - you could likely accomplish this better than I can.  An optional "copy runn start" might also be useful.  Please let me know if you have time to look into this, if not, I shall cobble away at it.  Thank you for your time.

**Comment by derek-shnosh** [comment]
> ...you could likely accomplish this better than I can...

I appreciate your vote of confidence here; however, full disclosure, I'm very new to programming and this script alone took me more time than I'd like to admit to get it to its current form. That's part of my learning experience though, no regrets (just a little shame 😉).

(Free)ZTP-Watcher was made to support a very limited use-case where the 2960S/X/XR platforms require a **.tar** file for upgrading firmware via auto-install (using FreeZTP). That's not to say that the script can't or won't be modified to accomplish other tasks over time, but at the moment I cannot currently allocate any time to add functionality to the script.

Feel free to fork the repo and modify as needed; also, I welcome any PR that improves or adds functionality. Keep in mind that @packetsar _may_ be introducing new features to [FreeZTP](https://github.com/PackeTsar/freeztp/issues/53#issuecomment-532772601) that completely negate the need for this script all together.

**Comment by derek-shnosh** [comment]
Regarding the `copy runn start`, the script does save the running config with a `write mem` (see [line 205](https://github.com/derek-shnosh/ztp-watcher/blob/1e647217f37ee9041546f900cd273c1b9ac3ab71/ztp-watcher.py#L205)). Are you requesting that this is changed to `copy run start` to be more platform agnostic; e.g. support NX-OS?

**Comment by helpdeskdan** [comment]
> , the script does save the running config with a write mem

Here I must blush and admit I had not more than glanced at your code.  My apologies.  That said, a copy runn start would be better. 

>Feel free to fork the repo and modify as needed

If I can stem the tide of random people showing up at my desk asking me how to do things they should already know how to do, I shall attempt more features.  Thank you for your time.

**Comment by derek-shnosh** [comment]
Closing issue as no changes will be implemented.
